In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [5]:
a.dtype

dtype('int32')

In [9]:
a=np.array([1,2,3],dtype='int16')

In [10]:
a=np.array([1,2,3.0],dtype='int16')

In [11]:
b=np.array([[1,2,3],[1.0,2.0,3.0]])

In [12]:
b.dtype

dtype('float64')

In [13]:
a.dtype

dtype('int16')

In [14]:
a.ndim

1

In [15]:
b.ndim

2

In [17]:
a.shape

(3,)

In [18]:
b.shape

(2, 3)

In [20]:
a=np.ones((2,3))

In [21]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [26]:
a=np.full((2,3),8)
a

array([[8, 8, 8],
       [8, 8, 8]])

In [27]:
a=np.repeat(a,3,axis=0)
a

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [28]:
a=np.repeat(a,3,axis=1)
a

array([[8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [30]:
a[1:-1,1:-1]=np.ones((4,7))
a

array([[8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 1, 1, 1, 1, 1, 1, 1, 8],
       [8, 1, 1, 1, 1, 1, 1, 1, 8],
       [8, 1, 1, 1, 1, 1, 1, 1, 8],
       [8, 1, 1, 1, 1, 1, 1, 1, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [31]:
b=a
b

array([[8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 1, 1, 1, 1, 1, 1, 1, 8],
       [8, 1, 1, 1, 1, 1, 1, 1, 8],
       [8, 1, 1, 1, 1, 1, 1, 1, 8],
       [8, 1, 1, 1, 1, 1, 1, 1, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [32]:
b[0]=1
print(b,a)

[[1 1 1 1 1 1 1 1 1]
 [8 1 1 1 1 1 1 1 8]
 [8 1 1 1 1 1 1 1 8]
 [8 1 1 1 1 1 1 1 8]
 [8 1 1 1 1 1 1 1 8]
 [8 8 8 8 8 8 8 8 8]] [[1 1 1 1 1 1 1 1 1]
 [8 1 1 1 1 1 1 1 8]
 [8 1 1 1 1 1 1 1 8]
 [8 1 1 1 1 1 1 1 8]
 [8 1 1 1 1 1 1 1 8]
 [8 8 8 8 8 8 8 8 8]]


In [34]:
b=a.copy()
b

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [8, 1, 1, 1, 1, 1, 1, 1, 8],
       [8, 1, 1, 1, 1, 1, 1, 1, 8],
       [8, 1, 1, 1, 1, 1, 1, 1, 8],
       [8, 1, 1, 1, 1, 1, 1, 1, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [35]:
b[0]=2
print(b)
print(a)

[[2 2 2 2 2 2 2 2 2]
 [8 1 1 1 1 1 1 1 8]
 [8 1 1 1 1 1 1 1 8]
 [8 1 1 1 1 1 1 1 8]
 [8 1 1 1 1 1 1 1 8]
 [8 8 8 8 8 8 8 8 8]]
[[1 1 1 1 1 1 1 1 1]
 [8 1 1 1 1 1 1 1 8]
 [8 1 1 1 1 1 1 1 8]
 [8 1 1 1 1 1 1 1 8]
 [8 1 1 1 1 1 1 1 8]
 [8 8 8 8 8 8 8 8 8]]


In [36]:
b.min()

1

In [37]:
b.min(axis=1)

array([2, 1, 1, 1, 1, 8])

In [38]:
b.sum()

182

In [39]:
b.mean()

3.3703703703703702